## Part 2

In [1]:
import json
with open('/Users/navnoorsingh/.secret/tmdb_api.json', 'r') as f:
    login = json.load(f)
## Display the keys of the loaded dict
login.keys()

dict_keys(['api-key'])

In [2]:
import tmdbsimple as tmdb
tmdb.API_KEY =  login['api-key']

In [3]:
## make a movie object using the .Movies function from tmdb
movie = tmdb.Movies(603)

info = movie.info()
info

{'adult': False,
 'backdrop_path': '/waCRuAW5ocONRehP556vPexVXA9.jpg',
 'belongs_to_collection': {'id': 2344,
  'name': 'The Matrix Collection',
  'poster_path': '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg',
  'backdrop_path': '/bRm2DEgUiYciDw3myHuYFInD7la.jpg'},
 'budget': 63000000,
 'genres': [{'id': 28, 'name': 'Action'},
  {'id': 878, 'name': 'Science Fiction'}],
 'homepage': 'http://www.warnerbros.com/matrix',
 'id': 603,
 'imdb_id': 'tt0133093',
 'original_language': 'en',
 'original_title': 'The Matrix',
 'overview': 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
 'popularity': 83.983,
 'poster_path': '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
 'production_companies': [{'id': 79,
   'logo_path': '/tpFpsqbleCzEE2p5EgvUq6ozfCA.png',
   'name': 'Village Roadshow Pictures',
   'origin_country': 'US'},
  {'id': 174,
   'logo_path': '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
   'name': 'Warner Bros. Pictures',
   'origin_country': 'US'},
  {'id': 372,
   'logo_path': None,
   'name': 'Groucho II Film Partnership',
   'origin_country': ''},
  {'id': 1885,
   'logo_path': '/tXMFoE8AtNdnFzWOW0aCLwl7xxS.png',
   'name': 'Silver Pictures',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '1999-03-30',
 'revenue': 463517383,
 'runtime': 136,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'Welcome to the Real World.',
 'title': 'The Matrix',
 'video': False,
 'vote_average': 8.2,
 'vote_count': 22749}

In [4]:
info['budget']

63000000

In [5]:
info['revenue']

463517383

In [6]:
info['imdb_id']

'tt0133093'

In [7]:
movie = tmdb.Movies('tt1361336')
info = movie.info()
info['budget']

50000000

In [8]:
response = movie.releases()

response

{'id': 587807,
 'countries': [{'certification': '',
   'descriptors': [],
   'iso_3166_1': 'CO',
   'primary': False,
   'release_date': '2021-02-12'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'US',
   'primary': False,
   'release_date': '2021-02-26'},
  {'certification': 'ALL',
   'descriptors': [],
   'iso_3166_1': 'KR',
   'primary': False,
   'release_date': '2021-02-24'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'ID',
   'primary': False,
   'release_date': '2021-03-10'},
  {'certification': '6',
   'descriptors': [],
   'iso_3166_1': 'NL',
   'primary': False,
   'release_date': '2021-06-09'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'IE',
   'primary': False,
   'release_date': '2021-05-07'},
  {'certification': 'M/6',
   'descriptors': [],
   'iso_3166_1': 'PT',
   'primary': False,
   'release_date': '2021-03-04'},
  {'certification': '6+',
   'descriptors': [],
   'iso_3166_1': 'RU',
   'primary': False,
   'release_date': '2021-02-25'},
  {'certification': 'L',
   'descriptors': [],
   'iso_3166_1': 'BR',
   'primary': False,
   'release_date': '2021-02-11'},
  {'certification': '7',
   'descriptors': [],
   'iso_3166_1': 'DK',
   'primary': False,
   'release_date': '2021-02-11'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'AU',
   'primary': False,
   'release_date': '2021-04-01'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'HK',
   'primary': False,
   'release_date': '2021-03-11'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'FR',
   'primary': False,
   'release_date': '2021-05-19'},
  {'certification': 'Btl',
   'descriptors': [],
   'iso_3166_1': 'SE',
   'primary': False,
   'release_date': '2021-05-28'},
  {'certification': '0',
   'descriptors': [],
   'iso_3166_1': 'DE',
   'primary': False,
   'release_date': '2021-06-17'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'CZ',
   'primary': False,
   'release_date': '2021-06-10'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'SK',
   'primary': False,
   'release_date': '2021-05-27'},
  {'certification': 'V',
   'descriptors': [],
   'iso_3166_1': 'LT',
   'primary': False,
   'release_date': '2021-05-07'},
  {'certification': '6',
   'descriptors': [],
   'iso_3166_1': 'HU',
   'primary': False,
   'release_date': '2021-05-20'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'PL',
   'primary': False,
   'release_date': '2021-06-11'},
  {'certification': '7',
   'descriptors': [],
   'iso_3166_1': 'ES',
   'primary': False,
   'release_date': '2021-03-26'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'SG',
   'primary': False,
   'release_date': '2021-02-11'},
  {'certification': 'Κ',
   'descriptors': [],
   'iso_3166_1': 'GR',
   'primary': False,
   'release_date': '2021-06-10'},
  {'certification': '普遍級',
   'descriptors': [],
   'iso_3166_1': 'TW',
   'primary': False,
   'release_date': '2021-02-10'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'US',
   'primary': False,
   'release_date': '2021-02-26'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'GB',
   'primary': False,
   'release_date': '2021-03-25'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'AU',
   'primary': False,
   'release_date': '2021-06-01'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'NZ',
   'primary': False,
   'release_date': '2021-06-01'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'FR',
   'primary': False,
   'release_date': '2021-09-16'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'FR',
   'primary': False,
   'release_date': '2022-02-16'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'GB',
   'primary': False,
   'release_date': '2021-05-24'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'AU',
   'primary': False,
   'release_date': '2021-06-21'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'US',
   'primary': False,
   'release_date': '2021-05-18'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'FR',
   'primary': False,
   'release_date': '2021-09-22'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'GR',
   'primary': False,
   'release_date': '2021-09-23'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'CA',
   'primary': False,
   'release_date': '2021-07-31'}]}

In [9]:
# example from package README
# source = https://github.com/celiao/tmdbsimple
releases = movie.releases()
for c in releases['countries']:
    if c['iso_3166_1'] == 'US':
        print(c['certification'])

PG
PG
PG

In [10]:
def get_movie_with_rating(movie_id):
    # Get the movie object for the current id
    movie = tmdb.Movies(movie_id)
    # save the .info .releases dictionaries
    info = movie.info()
    releases = movie.releases()
    # Loop through countries in releases
    for c in releases['countries']:
        # if the country abbreviation==US
        if c['iso_3166_1' ] =='US':
            ## save a "certification" key in the info dict with the certification
           info['certification'] = c['certification']
    return info

In [11]:
test = get_movie_with_rating("tt0848228") #put your function name here
test

{'adult': False,
 'backdrop_path': '/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
 'belongs_to_collection': {'id': 86311,
  'name': 'The Avengers Collection',
  'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
  'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
 'budget': 220000000,
 'genres': [{'id': 878, 'name': 'Science Fiction'},
  {'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'}],
 'homepage': 'https://www.marvel.com/movies/the-avengers',
 'id': 24428,
 'imdb_id': 'tt0848228',
 'original_language': 'en',
 'original_title': 'The Avengers',
 'overview': 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
 'popularity': 132.528,
 'poster_path': '/tYqp6vEOo8YlVWrYQvt9nyOhsA2.jpg',
 'production_companies': [{'id': 420,
   'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
   'name': 'Marvel Studios',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2012-04-25',
 'revenue': 1518815515,
 'runtime': 143,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'},
  {'english_name': 'Hindi', 'iso_639_1': 'hi', 'name': 'हिन्दी'},
  {'english_name': 'Russian', 'iso_639_1': 'ru', 'name': 'Pусский'}],
 'status': 'Released',
 'tagline': 'Some assembly required.',
 'title': 'The Avengers',
 'video': False,
 'vote_average': 7.707,
 'vote_count': 28138,
 'certification': 'PG-13'}

In [12]:
## testing our function by looping through a list of ids
import pandas as pd
test_ids = ["tt0848228", "tt0115937","tt0848228","tt0332280"]
results = []
errors = []
for movie_id in test_ids:
    
    try:
        movie_info = get_movie_with_rating(movie_id)
        results.append(movie_info)
        
    except Exception as e: 
        errors.append([movie_id, e])
    
pd.DataFrame(results)

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,certification
0,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,en,The Avengers,...,1518815515,143,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,7.707,28138,PG-13
1,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,en,The Avengers,...,1518815515,143,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,7.707,28138,PG-13
2,False,/qom1SZSENdmHFNZBXbtJAU0WTlC.jpg,None,29000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",http://www.newline.com/properties/notebookthe....,11036,tt0332280,en,The Notebook,...,115603229,123,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Behind every great love is a great story.,The Notebook,False,7.879,10120,PG-13

In [13]:
#designating the folder
import os, time,json
import tmdbsimple as tmdb 
from tqdm.notebook import tqdm_notebook
FOLDER = "Data/"
os.makedirs(FOLDER, exist_ok=True)
os.listdir(FOLDER)

['tmdb_api_CORRECTED_2_results_2000.json',
 'final_tmdb_data_2000.csv.gz',
 'tmdb_api_CORRECTED_3_results_2001.json',
 'title_basics.csv.gz',
 'tmdb_api_CORRECTED_2_results_2001.json',
 'final_tmdb_data_2001.csv.gz',
 '.ipynb_checkpoints',
 'CORRECTED_2_final_tmdb_data_2000.csv.gz',
 'title_akas.csv.gz',
 'title_ratings.csv.gz']

In [14]:
YEARS_TO_GET = [2000,2001]

import pandas as pd
basics = pd.read_csv('Data/title_basics.csv.gz')

basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001,NaN,118,"Comedy,Fantasy,Romance"
1,tt0062336,movie,The Tango of the Widower and Its Distorting Mi...,El tango del viudo y su espejo deformante,0,2020,NaN,70,Drama
2,tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018,NaN,122,Drama
3,tt0088751,movie,The Naked Monster,The Naked Monster,0,2005,NaN,100,"Comedy,Horror,Sci-Fi"
4,tt0096056,movie,Crime and Punishment,Crime and Punishment,0,2002,NaN,126,Drama

In [15]:
#this following code will not be used but has it as a reference

#'Adapted from: https: //www.geeksforgeeks.org/append-to-json-file-using-python"
def write_json (new_data, filename):
    with open (filename, 'r+') as file:
        # First we load existing data into a dict.
        file_data = json.load(file)
        ## Choose extend or append
        if (type (new_data) == list) & (type(file_data)== list):
            file_data.extend(new_data)
        else:
            file_data.append(new_data)
        # sets file's current position at offset.
        file.seek(0)
        #convert back to json.
        json.dump(file_data, file)

In [16]:
# i was able to get data for year 2000. 
# had trouble extracting the 2001 APIs
# just doing to make Year_to_get == 2001 only.

Year_to_Get = [2001]

#OUTER LOOP
for YEAR in tqdm_notebook(Year_to_Get, desc = 'YEARS', position = 0):
    #Defining the JSON file to store results for year
    JSON_FILE = f'{FOLDER}tmdb_api_CORRECTED_3_results_{YEAR}.json'
    
    # Check if file exists
    file_exists = os.path.isfile(JSON_FILE)

    # If it does not exist: create it
    if file_exists == False:
    # save an empty dict with just "imdb_id" to the new json file.
        with open(JSON_FILE,'w') as f:
            json.dump([{'imdb_id':0}],f)

    #Saving new year as the current df
    df = basics.loc[basics['startYear'] == YEAR].copy()

    #saving movie ids as list
    movie_ids = df['tconst'].copy() #.to_list()

    # Load existing data from json into a dataframe called "previous_df"
    previous_df = pd.read_json(JSON_FILE)

    # filter out any ids that are already in the JSON_FILE
    movie_ids_to_get = movie_ids[~movie_ids.isin(previous_df['imdb_id'])]


    #Get index and movie id from list
    # INNER Loop
    for movie_id in tqdm_notebook(movie_ids_to_get,
                                  desc=f'Movies from {YEAR}',
                                  position=1,
                                  leave=True):
        try: 
            # Retrieve then data for the movie id
            temp = get_movie_with_rating(movie_id)  
            # Append/extend results to existing file using a pre-made function
            write_json(temp,JSON_FILE)
            # Short 20 ms sleep to prevent overwhelming server
            time.sleep(0.02)
            
        except Exception as e:
            errors.append([movie_id, e])


    final_year_df = pd.read_json(JSON_FILE)
    final_year_df.to_csv(f"{FOLDER}CORRECTED_3_final_tmdb_data_{YEAR}.csv.gz", compression="gzip", index=False)

YEARS:   0%|          | 0/1 [00:00<?, ?it/s]

Movies from 2001:   0%|          | 0/1202 [00:00<?, ?it/s]